### ISSUE TITLE
Not working on OSX w/ VLC 3.0.8

### ISSUE THREAD

**Issue by petersj69** [surrim/vlc-delete#2] opened 2020-04-20 10:52 UTC
Hi,
this looks exactly like what I was looking for, unfortunately it doesn't seem to work on OSX with VLC 3.0.8. The extension is being displayed in the menu VLC/Extensions as "VLC Delete", but when activating it only seems to remove the item from the playlist, but not from the disk. I am not able to see any error messages or similar.

Regards

**Comment by surrim** [comment] 2020-08-14 09:12
Maybe you can add the MacOS command for removing files to code. I'm currently far away from home - only with bike ;)

**Comment by damianbeasock** [comment] 2020-12-30 03:55
Having a similar issue in Win10 (VLC 3.0.11), video is removed from playlist but the video file remains.

**Comment by surrim** [comment] 2020-12-31 19:57
> Having a similar issue in Win10 (VLC 3.0.11), video is removed from playlist but the video file remains.

I tried with VLC 3.0.11 x64 and it worked fine. The only thing I changed was the path of the script "C:\Program Files ~~(x86)~~\VideoLAN\VLC\lua\extensions\".

**Comment by damianbeasock** [comment] 2021-01-04 02:37
I determined this is happening when attempting to delete a file on a network drive (works flawlessly on OS disk and secondary hard drive). I've enabled every permission in windows I'm aware of but the file still remains on the network drive. Is it possible to delete from network locations? I can typically manipulate files on this drive as though they were on a local drive.

**Comment by surrim** [comment] 2023-06-17 17:26
Duplicate of https://github.com/surrim/vlc-delete/issues/9

@damianbeasock It's another issue, see https://github.com/surrim/vlc-delete/issues/14#issuecomment-1595058840

**Closed by surrim** 2023-06-17 17:26 UTC
Labels: duplicate
